"""RajVoiceCloner product branding (user-facing names and paths)."""

APP_NAME = "RajVoiceCloner"
APP_SLUG = "rajvoicecloner"
APP_TAGLINE = "Your personal voice AI platform"
APP_VERSION = "1.0.0"

# Default data lives under ~/.rajvoicecloner/studio.
DATA_DIR_ENV = "RAJVOICECLONER_DATA_DIR"
LEGACY_DATA_DIR_ENV = "RAJVOICEASSISTANT_DATA_DIR"

API_KEY_ENV = "RAJVOICECLONER_API_KEY"
LEGACY_API_KEY_ENV = "RAJVOICEASSISTANT_API_KEY"

LLM_URL_ENV = "RAJVOICECLONER_LLM_URL"
LEGACY_LLM_URL_ENV = "RAJVOICEASSISTANT_LLM_URL"

LLM_MODEL_ENV = "RAJVOICECLONER_LLM_MODEL"
LEGACY_LLM_MODEL_ENV = "RAJVOICEASSISTANT_LLM_MODEL"

LLM_API_KEY_ENV = "RAJVOICECLONER_LLM_API_KEY"
LEGACY_LLM_API_KEY_ENV = "RAJVOICEASSISTANT_LLM_API_KEY"

MODEL_ID = "rajvoice"
MODEL_DISPLAY_NAME = "RajVoice Engine"
